### ISSUE TITLE
Missing example for MAUI to create iOs-IPA-File

### ISSUE THREAD

**Issue by TopperDEL** [LanceMcCarthy/DevOpsExamples#49]
I can successfully build an .Net6 Multi-Target MAUI-project with this, but I don't get reliable info on how to package/publish it for store-submission. Could you elaborate on this?

**Comment by LanceMcCarthy** [comment]
It's still a bit early for production builds, it typically requires msbuild support (rather than dotnet build). We'll have more guidance when the tooling is ready in late spring 2022 (bookmark these docs https://docs.microsoft.com/en-us/dotnet/maui/). ​For example, search the Apple or Google Play Store for any MAUI applications ;) .NET MAUI is still in preview.

- See the .NET MAUI source code here => https://github.com/dotnet/maui 
- You can see the Microsoft build definitions here => https://dev.azure.com/xamarin/public/_build/results?buildId=52377&view=results  

In the meantime, I have reached out to my friends on the MAUI team so see if they can provide me with the right msbuild switches to produce a publishable ipa file that you can experiment with, but I wouldn't be surprised if Apple declines it. I suppose  if MAUI projects can deploy to emulator/device, it means that there is a provisioningProfile and certificate being used, and it might just be a matter of changing those values to use the store profile/certificate


Side Note: the WinUI3 project head is production ready. you can publish that MSIX immediately.

**Comment by LanceMcCarthy** [comment]
I heard back from Microsoft, they said it's not an official feature yet to be able to publish .NET MAUI projects to production endpoints.

However, they did point me to a StackOverflow post that is (to their knowledge) the most complete guide so far https://stackoverflow.com/questions/70437037/net-6-publishing-android-application/70440977#70440977

**Comment by TopperDEL** [comment]
Awesome answer and very, very helpful! I've searched Google for days now but did not use the correct search terms. And I thought MAUI was production ready already. Seems I missed that.

Thanks for your feedback!

**Comment by TopperDEL** [comment]
I got my IPA!
These where the commands used:
```
dotnet workload install android --ignore-failed-sources
dotnet workload install ios --ignore-failed-sources
dotnet workload install maccatalyst --ignore-failed-sources
dotnet workload install macos --ignore-failed-sources
dotnet workload install maui --ignore-failed-sources
dotnet restore MAUIProject.csproj
dotnet build MAUIProject.csproj -c Release -f net6.0-ios
dotnet publish MAUIProject.csproj -c Release -f:net6.0-ios /p:ArchiveOnBuild=true
```

I have the "Use .Net Core", "Install Apple certificate" and the "Install Apple provisioning profile" before in my pipeline.

**Comment by LanceMcCarthy** [comment]
Awesome! Where did you define the profile/certificate? Yes, you can install them to the runner/agent, but you need to tell the project which one to use. Was it in the csproj? Do you mind sharing an example that I can use to update these demos?

**Comment by TopperDEL** [comment]
Sure! I've added the Codesign-Properties like mentioned in the link you gave me. So I added this to my Mobile-csproj:
![image](https://user-images.githubusercontent.com/1833242/149718382-87f84707-5591-4c01-aea0-e1e40c22af6d.png)

I got the values from the files themselves. I installed the p12-certificate to my local machine (windows) and opened the user-certificate store where I got the name "iPhone Distribution: ..." that I pasted to "CodesignKey".
The CodeSign-Provision is the ID the pipeline renderes in the build-output of "Install an Apple provisioning profile":

![image](https://user-images.githubusercontent.com/1833242/149718638-c76b7d72-f1a3-4e54-8d2a-0da498480d37.png)

I was suprised that it suddenly worked. :) But my IPA is still not accepted by the store. But this should not be the IPA-creation-process but an error with my app itself. I've not yet tested it on any iOs-device yet. :)

Thanks for the hint with the workloads. This should shorten the build-time then, yes.

**Comment by TopperDEL** [comment]
Removing the "unnecessary workloads" from the task leads to errors. Even if I only build iOs here, I still have to install android and macos. Installing maui only leads to missing of macos and so on.
So I stick to the way it's currently working. :)

**Comment by LanceMcCarthy** [comment]
If it's not being accepted by the store, could you be accidentally be using the development cert instead of the company distribution cert? 

You also need to use the store profile instead of the beta profile (or vise versa if you're doing Test Flight release)

**Comment by TopperDEL** [comment]
No, that does not seem to be the problem - at least for the moment. It crashes on startup and is therefore not accepted for TestFlight-Distribution. I'm just lacking a Mac here currently, so I'm unable to identify the root problem. Oh how I hate Apple for their dev-pipeline....
